---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - EXTRA_VARS="anyenv_home='/Users/travis' anyenv_owner='travis' anyenv_group='staff' anyenv_profile='.bash_profile'"
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install ansible
        - ansible-galaxy install -r role_requirements.yml
        - bundle install
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - sudo groupadd jenkins
        - sudo useradd -s /bin/bash -d /home/jenkins -m -g jenkins jenkins
        - sudo pip install ansible
        - ansible-galaxy install -r role_requirements.yml
        - bundle install
      env:
        - TARGET=localhost_linux
        - EXTRA_VARS="anyenv_home='/home/travis' anyenv_owner='travis' anyenv_group='travis' anyenv_profile='.bash_profile'"
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name ${TARGET} ${IMAGE_NAME} /bin/sh
      after_script:
        - docker rm -f ${TARGET}
      env:
        - TARGET=container
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:debian-jessie
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name ${TARGET} ${IMAGE_NAME} /bin/sh
        - docker exec -it ${TARGET} groupadd jenkins
        - docker exec -it ${TARGET} useradd -s /bin/bash -d /home/jenkins -m -g jenkins jenkins
      after_script:
        - docker rm -f ${TARGET}
      env:
        - TARGET=container_with_specified_user
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:debian-jessie
        - EXTRA_VARS="anyenv_home='/home/jenkins' anyenv_owner='jenkins' anyenv_group='jenkins'"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install -r role_requirements.yml
  - bundle install

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --extra-vars="${EXTRA_VARS}" -vvvv
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
