---
# tasks file for ndenv(On Debian family)
- block:
  - name: Check whether ndenv is installed
    shell: "su -l -s {{ ndenv_login_shell }} -c 'ndenv versions' {{ anyenv_owner }}"
    # To suppress following warnings:
    #
    # TASK [FGtatsuro.ndenv : Install ndenv] *****************************************
    # [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running su
    #
    # Reason:
    #   become_method doesn't work well on container.
    #     - When become_method=sudo(default), almost containers don't have sudo command.
    #     - When become_method=su, docker connection plugin of Ansible doesn't allow 'su' as become_method.
    args:
      warn: no
    register: result_ndenv_versions
    ignore_errors: yes
    changed_when: no
  - name: Install ndenv
    shell: "su -l -s {{ ndenv_login_shell }} -c 'anyenv install ndenv' {{ anyenv_owner }}"
    args:
      warn: no
    when: "result_ndenv_versions.rc != 0"
  - name: Install nodejs
    shell: "su -l -s {{ ndenv_login_shell }} -c 'ndenv install {{ item }}' {{ anyenv_owner }}"
    args:
      warn: no
    when: "ndenv_node_versions is defined and item not in result_ndenv_versions.stdout"
    with_items: "{{ ndenv_node_versions }}"
  - name: Check default version
    shell: "su -l -s {{ ndenv_login_shell }} -c 'ndenv global' {{ anyenv_owner }}"
    args:
      warn: no
    register: result_ndenv_global
    changed_when: no
    when: "ndenv_global_version is defined"
  - name: Set default version
    shell: "su -l -s {{ ndenv_login_shell }} -c 'ndenv global {{ ndenv_global_version }}' {{ anyenv_owner }}"
    args:
      warn: no
    when: "ndenv_global_version is defined and ndenv_global_version not in result_ndenv_global.stdout"
  become: yes

