---
# tasks file for ndenv
- name: Run specified tasks on current platform
  include: "{{ ansible_os_family }}.yml"
- name: Check whether ndenv is installed
  shell: "/bin/bash -lc 'ndenv versions'"
  register: result_ndenv_versions
  ignore_errors: yes
  changed_when: no
- name: Install ndenv
  shell: "/bin/bash -lc 'anyenv install ndenv'"
  become: yes
  when: "result_ndenv_versions.rc != 0"
- name: Install nodejs
  shell: "/bin/bash -lc 'ndenv install {{ ndenv_node_version }}'"
  become: yes
  when: "ndenv_node_version is defined and ndenv_node_version not in result_ndenv_versions.stdout"
